name: tweet_gif_orthophoto

on:
  schedule:
    - cron: '50 0/1 * * *'  # a midi

jobs:
  tweet_gif_orthophoto-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        # run: Rscript -e 'install.packages(c("sf", "stringr", "dplyr","magick", "rtweet"), dependencies = TRUE)'
        run: |
        install.packages(c("sf", "stringr", "dplyr","magick"),type="binary")
        remotes::install_github("ropensci/rtweet")
      - name: Create gif and post tweet
        run: Rscript tweet_gif_orthophoto.R


